on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: .NET CI

jobs:
  test:
    name: Test .NET SDK
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

# Setup .NET and run tests
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
           dotnet-version: 8.0.100-rc.1.23463.5

      - name: Install WASI workload
        run: |
          dotnet workload install wasi-experimental

      - name: Test .NET Sdk
        run: |
          make test
